export default {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  ADD_TODO: "ADD_TODO",
  GET_TODOS: "GET_TODOS",
  REFRESH_TODOS: "REFRESH_TODOS",
  UPDATE_TODOS: "UPDATE_TODOS",
  GET_DB_ADDR: "GET_DB_ADDR",
};
